# Generated by Django 4.0.5 on 2022-08-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0003_shorturlmodel_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturlmodel',
            old_name='short_id',
            new_name='short_url',
        ),
    ]
